# Nome da base de dados no MongoDB
spring.data.mongodb.database=victor_bd

# Se o seu Mongo for local (Compass/Docker), use esta URI:
spring.data.mongodb.uri=mongodb://localhost:27017/vnavarro_db

# Mostrar os logs do Mongo no console (ajuda a saber se salvou mesmo)
logging.level.org.springframework.data.mongodb=DEBUG

# Porta em que a sua API vai rodar
server.port=8080